### ISSUE TITLE
Test on your machine

### ISSUE THREAD

**Issue by voidpirate** [voidpirate/m.net#5]
Please try compiling on your system. Once compiled a test binary should be produced`../bin/tests/Test` (what `Test` does is not important right now). When running `Test` you should see the following output printed to the console:
```
% ./bin/tests/Test
test ran
```

Travis-CI is failing for OS X and Linux builds as of right now, looks to be something from Travis side.

**Travis-CI (OS X)**
```
Linking CXX executable ../bin/tests/Test
duplicate symbol _main in:
    CMakeFiles/Test.dir/Test.cc.o
    CMakeFiles/Test.dir/test.cc.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/tests/Test] Error 1
make[1]: *** [tests/CMakeFiles/Test.dir/all] Error 2
make: *** [all] Error 2


The command "make" exited with 2.

Done. Your build exited with 1.
```

**Travis-CI (Linux)**
```
E: Unable to locate package qt55base
```

**Comment by voidpirate** [comment]
@netromdk

**Comment by voidpirate** [comment]
@netromdk

**Comment by netromdk** [comment]
Has been fixed. It was using Ubuntu Precise now on Linux so the qt55 repo had to be revised for launchpad. And also the dummy test was renamed because the test and test source file were different and thus it linked the test twice because the FS was case-insensitive. Going forward it's best to keep test name and source file the same, like "dummy" and "dummy.cc".
